apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: 'kustomize-deploy'
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dev/demo
    repoURL: >-
      https://github.com/abali01/Kustomize-argo-demo.git
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: false
