apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment
  name: service
spec:
  ports:
    - name: service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: health-port
      protocol: TCP
      port: 8081
      targetPort: 8081  
  selector:
    app: deployment
